spring.application.name=weatherapp
server.port=8080
lang=en

weather.api.key=c94ee1bd78604bd48ae15057260508
weather.api.url=https://api.weatherapi.com/v1/forecast.json

# Cấu hình H2 Database chạy mượt trên mọi server
spring.datasource.url=jdbc:h2:mem:weather_app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true